//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.16 at 02:58:23 PM CEST 
//


package com.tibco.xmlns.dd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.tibco.com/xmlns/dd}DeploymentDescriptorType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/xmlns/dd}ComponentSoftwareReference" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "componentSoftwareReference"
})
public class StartAsOneOf
    extends DeploymentDescriptorType
{

    @XmlElement(name = "ComponentSoftwareReference", required = true)
    protected List<ComponentSoftwareReference> componentSoftwareReference;

    /**
     * Gets the value of the componentSoftwareReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the componentSoftwareReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponentSoftwareReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComponentSoftwareReference }
     * 
     * 
     */
    public List<ComponentSoftwareReference> getComponentSoftwareReference() {
        if (componentSoftwareReference == null) {
            componentSoftwareReference = new ArrayList<ComponentSoftwareReference>();
        }
        return this.componentSoftwareReference;
    }

}
