//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.16 at 02:58:23 PM CEST 
//


package com.tibco.xmlns.applicationmanagement;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BWServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BWServiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.tibco.com/xmlns/ApplicationManagement}ServiceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}bwprocesses" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}checkpoints" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}isFt" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}faultTolerant" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}plugins" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BWServiceType", propOrder = {
    "bwprocesses",
    "checkpoints",
    "isFt",
    "faultTolerant",
    "plugins"
})
@XmlSeeAlso({
    Bw.class,
    FormFlow.class
})
public class BWServiceType
    extends ServiceType
{

    protected Bwprocesses bwprocesses;
    protected Checkpoints checkpoints;
    protected Boolean isFt;
    protected FaultTolerant faultTolerant;
    protected Plugins plugins;

    /**
     * Gets the value of the bwprocesses property.
     * 
     * @return
     *     possible object is
     *     {@link Bwprocesses }
     *     
     */
    public Bwprocesses getBwprocesses() {
        return bwprocesses;
    }

    /**
     * Sets the value of the bwprocesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bwprocesses }
     *     
     */
    public void setBwprocesses(Bwprocesses value) {
        this.bwprocesses = value;
    }

    /**
     * Gets the value of the checkpoints property.
     * 
     * @return
     *     possible object is
     *     {@link Checkpoints }
     *     
     */
    public Checkpoints getCheckpoints() {
        return checkpoints;
    }

    /**
     * Sets the value of the checkpoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Checkpoints }
     *     
     */
    public void setCheckpoints(Checkpoints value) {
        this.checkpoints = value;
    }

    /**
     * Gets the value of the isFt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFt() {
        return isFt;
    }

    /**
     * Sets the value of the isFt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFt(Boolean value) {
        this.isFt = value;
    }

    /**
     * Gets the value of the faultTolerant property.
     * 
     * @return
     *     possible object is
     *     {@link FaultTolerant }
     *     
     */
    public FaultTolerant getFaultTolerant() {
        return faultTolerant;
    }

    /**
     * Sets the value of the faultTolerant property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultTolerant }
     *     
     */
    public void setFaultTolerant(FaultTolerant value) {
        this.faultTolerant = value;
    }

    /**
     * Gets the value of the plugins property.
     * 
     * @return
     *     possible object is
     *     {@link Plugins }
     *     
     */
    public Plugins getPlugins() {
        return plugins;
    }

    /**
     * Sets the value of the plugins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plugins }
     *     
     */
    public void setPlugins(Plugins value) {
        this.plugins = value;
    }

}
