//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.16 at 02:58:23 PM CEST 
//


package com.tibco.xmlns.applicationmanagement;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.tibco.com/xmlns/ApplicationManagement}BWServiceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}authentications" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authentications"
})
public class FormFlow
    extends BWServiceType
{

    protected Authentications authentications;

    /**
     * Gets the value of the authentications property.
     * 
     * @return
     *     possible object is
     *     {@link Authentications }
     *     
     */
    public Authentications getAuthentications() {
        return authentications;
    }

    /**
     * Sets the value of the authentications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authentications }
     *     
     */
    public void setAuthentications(Authentications value) {
        this.authentications = value;
    }

}
