//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.16 at 02:58:23 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tibco.com/xmlns/ApplicationManagement",
									 xmlns={@XmlNs(namespaceURI = "http://www.tibco.com/xmlns/ApplicationManagement", prefix = ""),
											@XmlNs(namespaceURI = "http://www.tibco.com/xmlns/dd", prefix = "dd"),
											@XmlNs(namespaceURI = "http://www.tibco.com/xmlns/ApplicationManagement/BW", prefix = "bw"),
											@XmlNs(namespaceURI = "http://www.tibco.com/xmlns/authentication", prefix = "auth")},
									 elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tibco.xmlns.applicationmanagement;

import javax.xml.bind.annotation.XmlNs;
