//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.16 at 02:58:23 PM CEST 
//


package com.tibco.xmlns.authentication;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.tibco.com/xmlns/authentication}AuthenticationConfigurationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cookieDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cookiePath" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="requireNewSessionForVerify" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="protectWebServer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cookieDomain",
    "cookiePath",
    "requireNewSessionForVerify",
    "protectWebServer"
})
public class WebServerAuthenticationConfiguration
    extends AuthenticationConfigurationType
{

    protected String cookieDomain;
    @XmlElement(required = true)
    protected String cookiePath;
    protected boolean requireNewSessionForVerify;
    protected Boolean protectWebServer;

    /**
     * Gets the value of the cookieDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCookieDomain() {
        return cookieDomain;
    }

    /**
     * Sets the value of the cookieDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCookieDomain(String value) {
        this.cookieDomain = value;
    }

    /**
     * Gets the value of the cookiePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCookiePath() {
        return cookiePath;
    }

    /**
     * Sets the value of the cookiePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCookiePath(String value) {
        this.cookiePath = value;
    }

    /**
     * Gets the value of the requireNewSessionForVerify property.
     * 
     */
    public boolean isRequireNewSessionForVerify() {
        return requireNewSessionForVerify;
    }

    /**
     * Sets the value of the requireNewSessionForVerify property.
     * 
     */
    public void setRequireNewSessionForVerify(boolean value) {
        this.requireNewSessionForVerify = value;
    }

    /**
     * Gets the value of the protectWebServer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProtectWebServer() {
        return protectWebServer;
    }

    /**
     * Sets the value of the protectWebServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProtectWebServer(Boolean value) {
        this.protectWebServer = value;
    }

}
